name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --name "QuanteRunes" --icon=assets/icon.ico main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: QuanteRunes-Executable
        path: dist/QuanteRunes.exe 